// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/db1/",
  migrations: {
    path: "prisma/migrations1",
    seed: "tsx prisma/seed1.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL_1"],
  },
});
