// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/db2/",
  migrations: {
    path: "prisma/migrations2",
    seed: "tsx prisma/seed2.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL_2"],
  },
});
